"""add_onboarding_contacts_modules_user_types

Revision ID: 253f640e7a44
Revises: 3065e8d7891b
Create Date: 2026-01-08 10:29:36.672773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '253f640e7a44'
down_revision: Union[str, None] = '3065e8d7891b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_code', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('kyc_tier', sa.String(length=10), nullable=False),
    sa.Column('odoo_partner_id', sa.Integer(), nullable=True),
    sa.Column('erpnext_customer_id', sa.String(length=255), nullable=True),
    sa.Column('erpnext_supplier_id', sa.String(length=255), nullable=True),
    sa.Column('escalation_requested', sa.Boolean(), nullable=True),
    sa.Column('escalation_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['escalation_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'contact_code', name='unique_contact_code_per_tenant')
    )
    op.create_index('idx_contacts_escalation', 'contacts', ['tenant_id', 'escalation_requested'], unique=False)
    op.create_index('idx_contacts_tenant_type', 'contacts', ['tenant_id', 'contact_type'], unique=False)
    op.create_table('module_definitions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('onboarding_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('module_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('depends_on', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('setup_order', sa.Integer(), nullable=True),
    sa.Column('dependent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['depends_on'], ['module_definitions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_code'], ['module_definitions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', 'depends_on', name='unique_module_dependency')
    )
    op.create_index('idx_module_dependencies', 'module_dependencies', ['module_code'], unique=False)
    op.create_table('onboarding_templates',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('module_configurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('global_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_templates_system', 'onboarding_templates', ['is_system'], unique=False)
    op.create_table('permission_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('applies_to_user_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applies_to_contact_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_modifier', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'applies_to_user_types', name='unique_permission_scope')
    )
    op.create_table('tenant_onboarding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('steps_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_step', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index('idx_onboarding_status', 'tenant_onboarding', ['status'], unique=False)
    op.create_table('onboarding_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('step_code', sa.String(length=100), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=True),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['module_definitions.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['onboarding_id'], ['tenant_onboarding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_id', 'step_code', name='unique_onboarding_step')
    )
    op.create_index('idx_onboarding_steps', 'onboarding_steps', ['onboarding_id', 'status'], unique=False)
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    op.drop_column('users', 'user_type')
    op.drop_index('idx_onboarding_steps', table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_index('idx_onboarding_status', table_name='tenant_onboarding')
    op.drop_table('tenant_onboarding')
    op.drop_table('permission_scopes')
    op.drop_index('idx_templates_system', table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    op.drop_index('idx_module_dependencies', table_name='module_dependencies')
    op.drop_table('module_dependencies')
    op.drop_table('module_definitions')
    op.drop_index('idx_contacts_tenant_type', table_name='contacts')
    op.drop_index('idx_contacts_escalation', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
