"""create_missing_erp_tables

Revision ID: 65d1a23cba57
Revises: 5c7ba338aa55
Create Date: 2026-01-06 12:00:40.419292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65d1a23cba57'
down_revision: Union[str, None] = '5c7ba338aa55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_erp_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('erp_site_name', sa.String(length=100), nullable=False),
    sa.Column('erp_company_name', sa.String(length=200), nullable=False),
    sa.Column('erp_api_key', sa.String(length=200), nullable=True),
    sa.Column('erp_api_secret', sa.String(length=200), nullable=True),
    sa.Column('is_provisioned', sa.Boolean(), nullable=False),
    sa.Column('provisioned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_site_name'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_erp_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('enabled_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'module_code', name='unique_tenant_module')
    )
    op.create_index('idx_tenant_erp_modules_enabled', 'tenant_erp_modules', ['tenant_id', 'is_enabled'], unique=False)
    op.create_index('idx_tenant_erp_modules_tenant', 'tenant_erp_modules', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_memberships_primary_role_id'), table_name='memberships')
    op.drop_constraint(op.f('fk_memberships_primary_role'), 'memberships', type_='foreignkey')
    op.drop_column('memberships', 'primary_role_id')
    op.alter_column('permission_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_permission_overrides_permission_id'), table_name='permission_overrides')
    op.drop_index(op.f('idx_permission_overrides_user_tenant'), table_name='permission_overrides')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_permissions_code'), table_name='permissions')
    op.drop_index(op.f('idx_permissions_module'), table_name='permissions')
    op.add_column('role_audit_log', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('role_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_role_audit_log_action'), table_name='role_audit_log')
    op.drop_index(op.f('idx_role_audit_log_created_at'), table_name='role_audit_log')
    op.drop_index(op.f('idx_role_audit_log_tenant_id'), table_name='role_audit_log')
    op.drop_index(op.f('idx_role_audit_log_user_id'), table_name='role_audit_log')
    op.drop_column('role_audit_log', 'metadata')
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('idx_role_permissions_role_id'), table_name='role_permissions')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_roles_code'), table_name='roles')
    op.drop_index(op.f('idx_roles_tenant_id'), table_name='roles')
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_roles_active'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_tenant_id'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_user_id'), table_name='user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('idx_user_roles_active'), 'user_roles', ['is_active'], unique=False)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_roles_code'), 'roles', ['code'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('idx_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('role_audit_log', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_role_audit_log_user_id'), 'role_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_role_audit_log_tenant_id'), 'role_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_role_audit_log_created_at'), 'role_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_role_audit_log_action'), 'role_audit_log', ['action'], unique=False)
    op.alter_column('role_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('role_audit_log', 'extra_data')
    op.create_index(op.f('idx_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('idx_permissions_code'), 'permissions', ['code'], unique=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_permission_overrides_user_tenant'), 'permission_overrides', ['user_id', 'tenant_id'], unique=False)
    op.create_index(op.f('idx_permission_overrides_permission_id'), 'permission_overrides', ['permission_id'], unique=False)
    op.alter_column('permission_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('memberships', sa.Column('primary_role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_memberships_primary_role'), 'memberships', 'roles', ['primary_role_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_memberships_primary_role_id'), 'memberships', ['primary_role_id'], unique=False)
    op.drop_index('idx_tenant_erp_modules_tenant', table_name='tenant_erp_modules')
    op.drop_index('idx_tenant_erp_modules_enabled', table_name='tenant_erp_modules')
    op.drop_table('tenant_erp_modules')
    op.drop_table('tenant_erp_config')
    # ### end Alembic commands ###
