"""add configured_at to tenant_erp_modules

Revision ID: bffefa522f1e
Revises: 253f640e7a44
Create Date: 2026-01-08 11:21:40.589292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffefa522f1e'
down_revision: Union[str, None] = '253f640e7a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_erp_modules', sa.Column('configured_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_erp_modules', 'configured_at')
    # ### end Alembic commands ###
