"""initial schema

Revision ID: e14e2133956d
Revises: 
Create Date: 2026-01-26 09:17:47.227001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14e2133956d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('code')
    )

    # NOTE: contacts originally referenced users and tenants.
    # We'll create tenants and users first, then contacts to avoid FK ordering issues.

    op.create_table('module_definitions',
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('icon', sa.String(length=50), nullable=True),
        sa.Column('onboarding_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('default_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_core', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('code')
    )
    op.create_table('permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('permission_code', sa.String(length=50), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('module', sa.String(length=50), nullable=False),
        sa.Column('resource', sa.String(length=50), nullable=False),
        sa.Column('action', sa.String(length=20), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('permission_code')
    )
    op.create_table('tenants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_code', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('country_code', sa.String(length=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('engine', sa.String(length=20), nullable=True),
        sa.Column('provisioning_status', sa.String(length=20), nullable=True),
        sa.Column('provisioned_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('provisioning_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_code')
    )
    op.create_index('idx_tenants_provisioning_status', 'tenants', ['provisioning_status'], unique=False)

    # Create users table BEFORE contacts to ensure references from other tables succeed.
    # We intentionally omit the foreign key constraint on contact_id here (circular relationship).
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_code', sa.String(length=32), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('kyc_tier', sa.String(length=10), nullable=True),
        sa.Column('user_type', sa.String(length=20), nullable=True),
        sa.Column('contact_id', sa.UUID(), nullable=True),  # FK to contacts added later
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        # sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),  # added later
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('phone'),
        sa.UniqueConstraint('user_code')
    )

    op.create_table('kyc_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('previous_tier', sa.String(length=10), nullable=True),
        sa.Column('new_tier', sa.String(length=10), nullable=True),
        sa.Column('verified_by', sa.UUID(), nullable=True),
        sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('role', sa.String(length=30), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('invitation_code', sa.String(length=64), nullable=True),
        sa.Column('invited_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('invitation_code'),
        sa.UniqueConstraint('user_id', 'tenant_id', name='unique_membership')
    )
    op.create_table('module_dependencies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('module_code', sa.String(length=50), nullable=False),
        sa.Column('depends_on', sa.String(length=50), nullable=False),
        sa.Column('required', sa.Boolean(), nullable=True),
        sa.Column('setup_order', sa.Integer(), nullable=True),
        sa.Column('dependent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['depends_on'], ['module_definitions.code'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['module_code'], ['module_definitions.code'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('module_code', 'depends_on', name='unique_module_dependency')
    )
    op.create_index('idx_module_dependencies', 'module_dependencies', ['module_code'], unique=False)
    op.create_table('onboarding_templates',
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('module_configurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('global_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_templates_system', 'onboarding_templates', ['is_system'], unique=False)
    op.create_table('permission_overrides',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('grant_type', sa.String(length=10), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('granted_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_scopes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('applies_to_user_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('applies_to_contact_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('scope_modifier', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('permission_id', 'applies_to_user_types', name='unique_permission_scope')
    )
    op.create_table('roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('role_code', sa.String(length=50), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('scope', sa.String(length=20), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('role_code')
    )
    op.create_table('staff_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('staff_code', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'staff_code', name='unique_staff_code_per_tenant'),
        sa.UniqueConstraint('tenant_id', 'user_id', name='unique_staff_per_tenant')
    )
    op.create_table('tenant_erp_config',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('erp_site_name', sa.String(length=100), nullable=False),
        sa.Column('erp_company_name', sa.String(length=200), nullable=False),
        sa.Column('erp_api_key', sa.String(length=200), nullable=True),
        sa.Column('erp_api_secret', sa.String(length=200), nullable=True),
        sa.Column('is_provisioned', sa.Boolean(), nullable=False),
        sa.Column('provisioned_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('erp_site_name'),
        sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_erp_modules',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('module_code', sa.String(length=50), nullable=False),
        sa.Column('module_name', sa.String(length=100), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('enabled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('configured_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('enabled_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'module_code', name='unique_tenant_module')
    )
    op.create_index('idx_tenant_erp_modules_enabled', 'tenant_erp_modules', ['tenant_id', 'is_enabled'], unique=False)
    op.create_index('idx_tenant_erp_modules_tenant', 'tenant_erp_modules', ['tenant_id'], unique=False)
    op.create_table('tenant_notification_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('email_enabled', sa.Boolean(), nullable=True),
        sa.Column('email_new_user_invite', sa.Boolean(), nullable=True),
        sa.Column('email_role_changes', sa.Boolean(), nullable=True),
        sa.Column('email_payment_received', sa.Boolean(), nullable=True),
        sa.Column('email_invoice_generated', sa.Boolean(), nullable=True),
        sa.Column('email_order_status_change', sa.Boolean(), nullable=True),
        sa.Column('email_low_stock_alert', sa.Boolean(), nullable=True),
        sa.Column('email_monthly_report', sa.Boolean(), nullable=True),
        sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
        sa.Column('in_app_new_messages', sa.Boolean(), nullable=True),
        sa.Column('in_app_task_assignments', sa.Boolean(), nullable=True),
        sa.Column('in_app_approval_requests', sa.Boolean(), nullable=True),
        sa.Column('in_app_system_updates', sa.Boolean(), nullable=True),
        sa.Column('sms_enabled', sa.Boolean(), nullable=True),
        sa.Column('sms_order_confirmation', sa.Boolean(), nullable=True),
        sa.Column('sms_payment_received', sa.Boolean(), nullable=True),
        sa.Column('sms_important_alerts', sa.Boolean(), nullable=True),
        sa.Column('push_enabled', sa.Boolean(), nullable=True),
        sa.Column('push_instant_alerts', sa.Boolean(), nullable=True),
        sa.Column('push_daily_summary', sa.Boolean(), nullable=True),
        sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
        sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
        sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
        sa.Column('digest_frequency', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_onboarding',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('workspace_type', sa.String(length=50), nullable=True),
        sa.Column('template', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('current_step', sa.String(length=100), nullable=True),
        sa.Column('steps_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('provisioning_type', sa.String(length=20), nullable=True),
        sa.Column('provisioning_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('provisioning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('provisioning_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_step', sa.String(length=100), nullable=True),
        sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('started_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id')
    )
    op.create_index('idx_onboarding_status', 'tenant_onboarding', ['status'], unique=False)
    op.create_index('idx_tenant_onboarding_provisioning_status', 'tenant_onboarding', ['tenant_id', 'status'], unique=False)
    op.create_table('tenant_security_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('min_password_length', sa.Integer(), nullable=True),
        sa.Column('require_uppercase', sa.Boolean(), nullable=True),
        sa.Column('require_lowercase', sa.Boolean(), nullable=True),
        sa.Column('require_numbers', sa.Boolean(), nullable=True),
        sa.Column('require_special_chars', sa.Boolean(), nullable=True),
        sa.Column('password_expiry_days', sa.Integer(), nullable=True),
        sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
        sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True),
        sa.Column('require_mfa', sa.Boolean(), nullable=True),
        sa.Column('ip_whitelist_enabled', sa.Boolean(), nullable=True),
        sa.Column('ip_whitelist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('block_suspicious_activity', sa.Boolean(), nullable=True),
        sa.Column('enable_audit_log', sa.Boolean(), nullable=True),
        sa.Column('log_failed_login_attempts', sa.Boolean(), nullable=True),
        sa.Column('log_sensitive_operations', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_settings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('legal_name', sa.String(length=255), nullable=True),
        sa.Column('business_type', sa.String(length=100), nullable=True),
        sa.Column('registration_number', sa.String(length=100), nullable=True),
        sa.Column('tax_id', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('street_address', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state_province', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
        sa.Column('accounting_method', sa.String(length=50), nullable=True),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('employees_count', sa.Integer(), nullable=True),
        sa.Column('annual_revenue', sa.String(length=50), nullable=True),
        sa.Column('enable_invoicing', sa.Boolean(), nullable=True),
        sa.Column('enable_pos', sa.Boolean(), nullable=True),
        sa.Column('enable_inventory', sa.Boolean(), nullable=True),
        sa.Column('enable_hr', sa.Boolean(), nullable=True),
        sa.Column('enable_projects', sa.Boolean(), nullable=True),
        sa.Column('logo_url', sa.String(length=255), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('setup_completed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id')
    )
    op.create_table('onboarding_steps',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('onboarding_id', sa.UUID(), nullable=False),
        sa.Column('step_code', sa.String(length=100), nullable=False),
        sa.Column('module_code', sa.String(length=50), nullable=True),
        sa.Column('step_name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['module_code'], ['module_definitions.code'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['onboarding_id'], ['tenant_onboarding.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('onboarding_id', 'step_code', name='unique_onboarding_step')
    )
    op.create_index('idx_onboarding_steps', 'onboarding_steps', ['onboarding_id', 'status'], unique=False)
    op.create_table('role_audit_log',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('target_user_id', sa.UUID(), nullable=True),
        sa.Column('role_id', sa.UUID(), nullable=True),
        sa.Column('permission_id', sa.UUID(), nullable=True),
        sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )
    op.create_table('user_roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('assigned_by', sa.UUID(), nullable=True),
        sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'tenant_id', 'role_id', name='unique_user_tenant_role')
    )

    # Now create contacts AFTER tenants + users exist.
    # We avoid adding escalation_user_id FK here (added below) to break circular dependency.
    op.create_table('contacts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('contact_code', sa.String(length=50), nullable=False),
        sa.Column('contact_name', sa.String(length=255), nullable=False),
        sa.Column('contact_type', sa.String(length=20), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('address', sa.String(length=500), nullable=True),
        sa.Column('kyc_tier', sa.String(length=10), nullable=False),
        sa.Column('odoo_partner_id', sa.Integer(), nullable=True),
        sa.Column('erpnext_customer_id', sa.String(length=255), nullable=True),
        sa.Column('erpnext_supplier_id', sa.String(length=255), nullable=True),
        sa.Column('escalation_requested', sa.Boolean(), nullable=True),
        sa.Column('escalation_user_id', sa.UUID(), nullable=True),  # FK added later
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        # sa.ForeignKeyConstraint(['escalation_user_id'], ['users.id'], ondelete='SET NULL'),  # added later
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'contact_code', name='unique_contact_code_per_tenant')
    )
    op.create_index('idx_contacts_escalation', 'contacts', ['tenant_id', 'escalation_requested'], unique=False)
    op.create_index('idx_contacts_tenant_type', 'contacts', ['tenant_id', 'contact_type'], unique=False)

    # ### end Alembic commands ###

    # Add the two foreign keys that create the circular reference now that both tables exist.
    op.create_foreign_key(
        'fk_users_contact', 'users', 'contacts',
        ['contact_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_contacts_escalation_user', 'contacts', 'users',
        ['escalation_user_id'], ['id'], ondelete='SET NULL'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the FKs added at the end first
    op.drop_constraint('fk_contacts_escalation_user', 'contacts', type_='foreignkey')
    op.drop_constraint('fk_users_contact', 'users', type_='foreignkey')

    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('role_audit_log')
    op.drop_index('idx_onboarding_steps', table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_table('tenant_settings')
    op.drop_table('tenant_security_settings')
    op.drop_index('idx_tenant_onboarding_provisioning_status', table_name='tenant_onboarding')
    op.drop_index('idx_onboarding_status', table_name='tenant_onboarding')
    op.drop_table('tenant_onboarding')
    op.drop_table('tenant_notification_settings')
    op.drop_index('idx_tenant_erp_modules_tenant', table_name='tenant_erp_modules')
    op.drop_index('idx_tenant_erp_modules_enabled', table_name='tenant_erp_modules')
    op.drop_table('tenant_erp_modules')
    op.drop_table('tenant_erp_config')
    op.drop_table('staff_profiles')
    op.drop_table('roles')
    op.drop_table('permission_scopes')
    op.drop_table('permission_overrides')
    op.drop_index('idx_templates_system', table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    op.drop_index('idx_module_dependencies', table_name='module_dependencies')
    op.drop_table('module_dependencies')
    op.drop_table('memberships')
    op.drop_table('kyc_logs')
    op.drop_table('users')
    op.drop_index('idx_tenants_provisioning_status', table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('permissions')
    op.drop_table('module_definitions')
    op.drop_index('idx_contacts_tenant_type', table_name='contacts')
    op.drop_index('idx_contacts_escalation', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
