"""Add engine to tenants retry

Revision ID: fc75fd1695eb
Revises: 5b34e64bb657
Create Date: 2026-01-05 23:03:20.221408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc75fd1695eb'
down_revision: Union[str, None] = '5b34e64bb657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('engine', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'engine')
    # ### end Alembic commands ###
